### ISSUE TITLE
Error when running run_event_log_anonymizer.py with CreditReq dataset on 0.3

### ISSUE THREAD

**Issue by paul-cvp** [Elkoumy/amun#1]
The error I'm getting:
`Processing the dataset: CreditReq
with Delta: 0.2 , and precision: 0.2
DoneTraceback (most recent call last):
  File "run_event_log_anonymizer.py", line 152, in <module>
    anonymize_event_log(data_dir,out_dir,experiment_log_dir,dataset,mode,delta,precision,iteration)
  File "run_event_log_anonymizer.py", line 33, in anonymize_event_log
    data, variants_count = event_log_anonymization(data_dir, dataset, mode, delta, precision, temp_dir)
  File "/c/Projects/amun/amun/event_log_anonymization.py", line 23, in event_log_anonymization
    data, variants_count = xes_to_DAFSA(data_dir, dataset)
  File "/c/Projects/amun/amun/input_module.py", line 143, in xes_to_DAFSA
    data = annotate_eventlog_with_state_vectorized(data, data_dir, dataset, trace_variants)
  File "/c/Projects/amun/amun/input_module.py", line 501, in annotate_eventlog_with_state_vectorized
    trace_variants_df = trace_variants_df.groupby(['trace_variant']).apply(annotate_state_per_case, dafsa_states=dafsa_states).reset_index()
  File "/home/vco/.pyenv/versions/amun/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1272, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "/home/vco/.pyenv/versions/amun/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1306, in _python_apply_general
    keys, values, mutated = self.grouper.apply(f, data, self.axis)
  File "/home/vco/.pyenv/versions/amun/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 783, in apply
    result_values, mutated = splitter.fast_apply(f, sdata, group_keys)
  File "/home/vco/.pyenv/versions/amun/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 1328, in fast_apply
    return libreduction.apply_frame_axis0(sdata, f, names, starts, ends)
  File "pandas/_libs/reduction.pyx", line 381, in pandas._libs.reduction.apply_frame_axis0
  File "/home/vco/.pyenv/versions/amun/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1256, in f
    return func(g, *args, **kwargs)
  File "/c/Projects/amun/amun/input_module.py", line 469, in annotate_state_per_case
    curr_state= dafsa_states[prev_state][row['concept:name']]
KeyError: 'Collection of documents'`

Please help. Am I doing something wrong? Or am I running on the wrong branch? Thank you!

**Comment by paul-cvp** [comment]
Turns out it works on the Traffic dataset.

**Comment by Elkoumy** [comment]
Hello Paul,
The framework (as mentioned in the published paper) assumes that there are only 3 columns in the event log: Case Id, Activity label, and timestamp. 
The latest version of the framework has new features, but not published yet. 
If you have any future comments or questions, feel free to reach me.

**Comment by Elkoumy** [comment]
Hi Again,
You can use the file Amun.py to run the system. For more details, please check the updated ReadMe file.
